/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package psproject_v5.ui.form.panel.impl;

import java.util.logging.Level;
import java.util.logging.Logger;
import psproject_v5.ui.components.validator.IValidator;
import psproject_v5.exception.ValidatorException;
import psproject_v5.ui.form.panel.IPanelComponent;

/**
 *
 * @author aleks
 */
public class PnlTextField extends javax.swing.JPanel implements IPanelComponent {

    private IValidator validator;

    /**
     * Creates new form PnlTextField
     */
    public PnlTextField() {
        initComponents();
        preparePanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStaticText = new javax.swing.JLabel();
        lblErrorText = new javax.swing.JLabel();
        txtText = new javax.swing.JTextField();

        lblStaticText.setText("jLabel1");

        lblErrorText.setForeground(new java.awt.Color(255, 0, 51));
        lblErrorText.setText("jLabel1");

        txtText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStaticText, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtText, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE))
                    .addComponent(lblErrorText, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStaticText)
                    .addComponent(txtText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblErrorText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public IValidator getValidator() {
        return validator;
    }

    public void setValidator(IValidator validator) {
        this.validator = validator;
    }

    @Override
    public void setStaticText(String staticTxt) {
        lblStaticText.setText(staticTxt);
    }

    @Override
    public void setErrorText(String errorTxt) {
        lblErrorText.setText(errorTxt);
    }

    @Override
    public Object getValue() throws Exception{
        setErrorText(" ");
        String text = txtText.getText().trim();
        if (validator != null) {
            try {
                validator.validate(text);
                return text;
            } catch (ValidatorException ex) {
                setErrorText(ex.getMessage());
                throw ex;
            }
        }
        return text;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblErrorText;
    private javax.swing.JLabel lblStaticText;
    private javax.swing.JTextField txtText;
    // End of variables declaration//GEN-END:variables

    @Override
    public void preparePanel() {
        setErrorText("");
        txtText.setText("");
    }

    @Override
    public void setValue(Object value) {
        txtText.setText(String.valueOf(value));
    }

    @Override
    public void setPnlEnabled(boolean enabled) {
        txtText.setEnabled(enabled);
    }

    @Override
    public void setPnlVisible(boolean visible) {
//        txtText.setVisible(visible);
        setVisible(visible);
    }
}
