/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package psproject_v5.ui.form;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.time.LocalDate;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author aleks
 */
public class FrmDatePicker extends javax.swing.JDialog {

    private LocalDate date;
    private LocalDate previousDate;
//    private Action actionChoose; 

    /**
     * Creates new form FrmDatePicker
     */
    public FrmDatePicker(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        setLocationRelativeTo(null);
        initComponents();
        prepareForm();
        setKeyBinding();
//        setFocusable(false);
    }

    public LocalDate getPreviousDate() {
        return previousDate;
    }

    public void setPreviousDate(LocalDate previousDate) {
        this.previousDate = previousDate;
    }
    
    public LocalDate getDate() {
        if(date!=null)
            return date;     
        else
            return previousDate;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDate3CMB1 = new psproject_v5.ui.form.panel.impl.PnlDate3CMB();
        btnChoose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnChoose.setText("Choose date");
        btnChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDate3CMB1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDate3CMB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChoose)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseActionPerformed

        try {
            pnlDate3CMB1.setErrorText("");
            date = LocalDate.parse(pnlDate3CMB1.getValue().toString());
        } catch (Exception e) {
            pnlDate3CMB1.setErrorText(e.getMessage());
            JOptionPane.showMessageDialog(null, "Date does not exist");
        }
        setVisible(false);

    }//GEN-LAST:event_btnChooseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChoose;
    private psproject_v5.ui.form.panel.impl.PnlDate3CMB pnlDate3CMB1;
    // End of variables declaration//GEN-END:variables

    private void prepareForm() {
        pnlDate3CMB1.setStaticText("Select date:");

    }

    private void setKeyBinding() {
        btnChoose.getInputMap().put(KeyStroke.getKeyStroke("ENTER"), "choose");
        btnChoose.getActionMap().put("choose", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
            pnlDate3CMB1.setErrorText("");
            date = LocalDate.parse(pnlDate3CMB1.getValue().toString());
        } catch (Exception ex) {
            pnlDate3CMB1.setErrorText(ex.getMessage());
            JOptionPane.showMessageDialog(null, "Date does not exist");
        }
        setVisible(false);
            }
        });
    }
}
