/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package psproject_v5.ui.form;


import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import psproject_v5.communication.Communication;
import psproject_v5.communication.ObjectWrapper;
import psproject_v5.constants.MyConstants;
import psproject_v5.controller.Controller;
import psproject_v5.help.Helper;
import psproject_v5.domain.Employee;
import psproject_v5.session.Session;
import psproject_v5.threads.ReceiverThread;
import psproject_v5.ui.form.util.FollowingForm;
import psproject_v5.ui.form.util.FormMode;
import psproject_v5.communication.Operation;
import psproject_v5.communication.Request;

/**
 *
 * @author aleks
 */
public class FrmMain extends javax.swing.JFrame {

    private final ReceiverThread receiverThread;

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        receiverThread = new ReceiverThread();
        receiverThread.start();
        Session.getInstance().addItem("mainForm", this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImage = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuDepartment = new javax.swing.JMenu();
        menuDepartmentItemView = new javax.swing.JMenuItem();
        menuEmployee = new javax.swing.JMenu();
        menuEmployeeItemAdd = new javax.swing.JMenuItem();
        menuEmployeeItemView = new javax.swing.JMenuItem();
        menuReport = new javax.swing.JMenu();
        menuReportItemFaculty = new javax.swing.JMenuItem();
        menuReportItemDepartment = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dobraSlika - Copy.jpg"))); // NOI18N
        lblImage.setMaximumSize(getPreferredSize());

        menuDepartment.setText("Department");

        menuDepartmentItemView.setText("View");
        menuDepartmentItemView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDepartmentItemViewActionPerformed(evt);
            }
        });
        menuDepartment.add(menuDepartmentItemView);

        jMenuBar1.add(menuDepartment);

        menuEmployee.setText("Employee");

        menuEmployeeItemAdd.setText("Add");
        menuEmployeeItemAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEmployeeItemAddActionPerformed(evt);
            }
        });
        menuEmployee.add(menuEmployeeItemAdd);

        menuEmployeeItemView.setText("View");
        menuEmployeeItemView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEmployeeItemViewActionPerformed(evt);
            }
        });
        menuEmployee.add(menuEmployeeItemView);

        jMenuBar1.add(menuEmployee);

        menuReport.setText("Report");

        menuReportItemFaculty.setText("Faculty");
        menuReportItemFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportItemFacultyActionPerformed(evt);
            }
        });
        menuReport.add(menuReportItemFaculty);

        menuReportItemDepartment.setText("Department");
        menuReportItemDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportItemDepartmentActionPerformed(evt);
            }
        });
        menuReport.add(menuReportItemDepartment);

        jMenuBar1.add(menuReport);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuDepartmentItemViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDepartmentItemViewActionPerformed
//        Session.getInstance().removeItem("afterSelection");
        Session.getInstance().addItem("afterSelection", FollowingForm.VIEW);
        FrmViewAllDepartments frmViewAllDepartments = new FrmViewAllDepartments(null, true);
        Helper.centerDialog(frmViewAllDepartments);
        frmViewAllDepartments.setVisible(true);
    }//GEN-LAST:event_menuDepartmentItemViewActionPerformed

    private void menuEmployeeItemAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEmployeeItemAddActionPerformed
        FrmEmployee frmEmployee = new FrmEmployee(null, true, FormMode.ADD_MODE);
        Helper.centerDialog(frmEmployee);
        frmEmployee.setVisible(true);
    }//GEN-LAST:event_menuEmployeeItemAddActionPerformed

    private void menuEmployeeItemViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEmployeeItemViewActionPerformed
        FrmViewAllEmployees frmViewAllEmployees = new FrmViewAllEmployees(null, true);
        Helper.centerDialog(frmViewAllEmployees);
        frmViewAllEmployees.setVisible(true);
    }//GEN-LAST:event_menuEmployeeItemViewActionPerformed

    private void menuReportItemFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportItemFacultyActionPerformed
        try {
            // GET EMPLOYEES FROM SERVER
            List<Employee> employees = Controller.getInstance().getAllEmployees();
            
            FrmReportAcademicTitle frmReportAcademicTitle = new FrmReportAcademicTitle(this, true, employees);
            Helper.centerDialog(frmReportAcademicTitle);
            frmReportAcademicTitle.setVisible(true);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menuReportItemFacultyActionPerformed

    private void menuReportItemDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportItemDepartmentActionPerformed
        
        //programski odluciti sta ce da se radi sa selektovanim departmentom
        Session.getInstance().addItem("afterSelection", FollowingForm.REPORT);
        
        FrmViewAllDepartments frmViewAllDepartments = new FrmViewAllDepartments(null, true);
        Helper.centerDialog(frmViewAllDepartments);
        frmViewAllDepartments.setVisible(true);

    }//GEN-LAST:event_menuReportItemDepartmentActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JMenu menuDepartment;
    private javax.swing.JMenuItem menuDepartmentItemView;
    private javax.swing.JMenu menuEmployee;
    private javax.swing.JMenuItem menuEmployeeItemAdd;
    private javax.swing.JMenuItem menuEmployeeItemView;
    private javax.swing.JMenu menuReport;
    private javax.swing.JMenuItem menuReportItemDepartment;
    private javax.swing.JMenuItem menuReportItemFaculty;
    // End of variables declaration//GEN-END:variables
}
